### PR TITLE
Rewrite CMake for proper install/uninstall. Merge useful improvements from others

### PR DESCRIPTION
**Pull request by ahundt**
I've rewritten the CMake script so it can install and uninstall completely, plus generate config scripts for others to include your library easily. 

I also found a few other people had made some nice changes, so I merged them in as well.

### CODE REVIEW

**Comment by mp3guy** [comment]
Thanks for putting this all together. But I'm not going to merge this into my branch, since it's not intended to be an installable project, just a simple standalone example application. I can refer people to your fork if they want to be able to install it.

**Comment by ahundt** [comment]
I see, you aren't intending it to be used by other libraries?

**Comment by mp3guy** [comment]
No, especially since it contains two different methods (why would anyone want the slower method?) and also it has benchmarking build it. The class and code for the fast method are pretty independent so easy to just drop into an existing project.

**Comment by ahundt** [comment]
Well the slower method is probably useful for those who want to run something but don't have a gpu in every machine they code on. :-) 

I also went deeper into the code and now see it is for frame-frame registration and doesn't include frame-cloud. Could potentially be useful for my cases when I have two cameras that need to be registered (also needed) but in my case frame-cloud is my primary use case. Will still use it as a reference to learn from. Thanks!

**Comment by mp3guy** [comment]
The slower method is also CUDA. Just the reduction is done less efficiently. 

For frame cloud you just need to solve the data association somehow on the GPU, so a kd-tree or something.

**Pull request closed without merging**
